# Audit application
name: Audit Application

on: [pull_request]

jobs:
  audit-application:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Check out source code
        uses: actions/checkout@v3

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Setup pnpm
      - name: Setup pnpm
        run: npm install -g pnpm

      # Get node_modules cache
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: cache-node-modules

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Get app version from package.json
      - name: Set app environment varibales
        run: echo "REACT_APP_VERSION=$(pnpm pkg get version)" >> $GITHUB_ENV

      # Build application
      - name: Build project
        run: pnpm run build

      # Deploy application
      - name: Audit application
        env:
          CI: true
        run: pnpm audit
